#ifndef YANDEX_TRAINING_CONTEST_BACKEND_E_ZANIMATELNAYA_ALHIMIYA_TEST_TEST_H
#define YANDEX_TRAINING_CONTEST_BACKEND_E_ZANIMATELNAYA_ALHIMIYA_TEST_TEST_H

#include <gtest/gtest.h>
#include <sys/wait.h>
#include <unistd.h>

#include <array>

#endif  // YANDEX_TRAINING_CONTEST_BACKEND_E_ZANIMATELNAYA_ALHIMIYA_TEST_TEST_H